services:
  backend:
    image: blog-backend-dev
    build:
      context: ./backend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3003:3003
  frontend:
    image: blog-frontend-dev
    build:
      context: ./frontend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app #
    ports:
      - 3000:3000
    depends_on:
      - backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend
