POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "root",
  "password": "iamtherootuser"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "AC",
  "name": "AC",
  "password": "ACisalmosRoot"
}

### duplicate
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "root",
  "password": "iamtherootuser"
}